spring:
  config:
    import: "configserver:http://localhost:8888"
  datasource:
    url: jdbc:postgresql://ep-patient-thunder-aheic3kc.c-3.us-east-1.aws.neon.tech/candysoft?sslmode=require&channelBinding=require
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8093
logging:
  level:
    org.springframework.cloud.config.client: DEBUG